exclude: ".*snap$"
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
            exclude_types: [pem]
          - id: check-merge-conflict
          - id: debug-statements
          - id: end-of-file-fixer
    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: "v0.1.6"
      hooks:
          - id: ruff-format
