exclude: ".*snap$"
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.4.0
      hooks:
          - id: trailing-whitespace
            exclude_types: [pem]
          - id: check-merge-conflict
          - id: debug-statements
    - repo: https://github.com/antonbabenko/pre-commit-terraform
      rev: v1.76.0
      hooks:
        - id: terraform_fmt
        - id: terraform_validate
    - repo: https://github.com/pycqa/flake8
      rev: 3.9.2
      hooks:
        - id: flake8
          additional_dependencies: [
            "flake8-comprehensions",
            "flake8-pep3101",
            "flake8-bugbear",
            "flake8-debugger",
            "flake8-tidy-imports"
          ]
    - repo: https://github.com/asottile/pyupgrade
      rev: v2.37.3
      hooks:
        - id: pyupgrade
          args: [ --py38-plus ]
    - repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
        - id: isort
          name: isort (python)
    - repo: https://github.com/psf/black
      rev: 22.10.0
      hooks:
        - id: black
          args: [ --line-length=100, --safe ]
